package com.mozhimen.emulatork.input

/**
 * @ClassName TouchKind
 * @Description TODO
 * @Author Mozhimen & Kolin Zhao
 * @Date 2024/5/22
 * @Version 1.0
 */
enum class InputKind {
    GB_LEFT,
    GB_RIGHT,
    NES_LEFT,
    NES_RIGHT,
    DESMUME_LEFT,
    DESMUME_RIGHT,
    MELONDS_NDS_LEFT,
    MELONDS_NDS_RIGHT,
    PSX_LEFT,
    PSX_RIGHT,
    PSX_DUALSHOCK_LEFT,
    PSX_DUALSHOCK_RIGHT,
    PSP_LEFT,
    PSP_RIGHT,
    SNES_LEFT,
    SNES_RIGHT,
    GBA_LEFT,
    GBA_RIGHT,
    SMS_LEFT,
    SMS_RIGHT,
    GG_LEFT,
    GG_RIGHT,
    LYNX_LEFT,
    LYNX_RIGHT,
    PCE_LEFT,
    PCE_RIGHT,
    DOS_LEFT,
    DOS_RIGHT,
    NGP_LEFT,
    NGP_RIGHT,
    WS_LANDSCAPE_LEFT,
    WS_LANDSCAPE_RIGHT,
    WS_PORTRAIT_LEFT,
    WS_PORTRAIT_RIGHT,
    N64_LEFT,
    N64_RIGHT,
    GENESIS_3_LEFT,
    GENESIS_3_RIGHT,
    GENESIS_6_LEFT,
    GENESIS_6_RIGHT,
    ATARI2600_LEFT,
    ATARI2600_RIGHT,
    ARCADE_4_LEFT,
    ARCADE_4_RIGHT,
    ARCADE_6_LEFT,
    ARCADE_6_RIGHT,
    ATARI7800_LEFT,
    ATARI7800_RIGHT,
    NINTENDO_3DS_LEFT,
    NINTENDO_3DS_RIGHT
}